import { useState } from 'react';

const API = `${import.meta.env.VITE_API_URL || `${window.location.protocol}//${window.location.hostname}:5000`}/api/customer-portal`;

async function portalRequest(path, options = {}, token = '') {
  const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...options });
  const payload = await response.json();
  if (!response.ok) throw new Error(payload?.error?.message || 'Não foi possível concluir a operação.');
  return payload;
}

const emptyForm = { nome: '', documento: '', telefone: '', email: '', password: '' };
const emptyOrder = { equipamento: '', defeito: '', forma_pagamento: 'Pix' };

export default function CustomerPortal({ onBack }) {
  const [mode, setMode] = useState('login');
  const [session, setSession] = useState(null);
  const [form, setForm] = useState(emptyForm);
  const [orderForm, setOrderForm] = useState(emptyOrder);
  const [orders, setOrders] = useState([]);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const [shippingLabel, setShippingLabel] = useState(null);

  const update = (event, setter) => { const { name, value } = event.target; setter((current) => ({ ...current, [name]: value })); };
  const submitAccess = async (event) => { event.preventDefault(); setError(''); try { const response = await portalRequest(mode === 'login' ? '/login' : '/register', { method: 'POST', body: JSON.stringify(form) }); setSession(response.data); setMessage('Acesso do cliente realizado.'); const ordersResponse = await portalRequest('/orders', {}, response.data.token); setOrders(ordersResponse.data || []); } catch (requestError) { setError(requestError.message); } };
  const submitOrder = async (event) => { event.preventDefault(); setError(''); try { const response = await portalRequest('/orders', { method: 'POST', body: JSON.stringify(orderForm) }, session.token); setOrders((current) => [response.data, ...current]); setOrderForm(emptyOrder); setMessage(`Ordem ${response.data.protocolo} aberta com sucesso.`); } catch (requestError) { setError(requestError.message); } };
  const loadLabel = async (order) => { try { const response = await portalRequest(`/orders/${order.id}/shipping-label`, {}, session.token); setShippingLabel(response.data); } catch (requestError) { setError(requestError.message); } };

  if (!session) return <main className="customer-portal-shell"><section className="customer-portal-card customer-access-card"><div className="access-card-inner"><aside className="access-visual-panel"><button className="portal-back" type="button" onClick={onBack}>Voltar ao acesso interno</button><span className="eyebrow">Área do cliente</span><h1>{mode === 'login' ? 'Acompanhe seu atendimento' : 'Crie seu acesso'}</h1><p className="login-copy">Abra solicitações, informe o pagamento e acompanhe suas ordens em um só lugar.</p><ul className="access-benefits"><li>Solicitações centralizadas</li><li>Pagamentos e status em tempo real</li><li>Atendimento mais ágil</li></ul></aside><div className="access-form-panel"><div className="access-form-header"><span className="access-badge">{mode === 'login' ? 'Login' : 'Cadastro'}</span></div><form className="entity-form access-form" onSubmit={submitAccess}>{mode === 'register' && <><label>Nome completo<input name="nome" value={form.nome} onChange={(event) => update(event, setForm)} placeholder="Digite seu nome completo" required /></label><div className="two-column-fields"><label>Documento<input name="documento" value={form.documento} onChange={(event) => update(event, setForm)} placeholder="CPF ou CNPJ" required /></label><label>Telefone<input name="telefone" value={form.telefone} onChange={(event) => update(event, setForm)} placeholder="(00) 00000-0000" /></label></div></>}<label>E-mail<input name="email" type="email" value={form.email} onChange={(event) => update(event, setForm)} placeholder="seu@email.com" required /></label><label>Senha<input name="password" type="password" minLength="6" value={form.password} onChange={(event) => update(event, setForm)} placeholder="Mínimo 6 caracteres" required /></label>{error && <p className="form-error">{error}</p>}<button className="primary-button access-submit" type="submit">{mode === 'login' ? 'Entrar como cliente' : 'Cadastrar acesso'}</button></form><button className="portal-switch" type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'Ainda não tenho cadastro' : 'Já tenho cadastro'}</button></div></div></section></main>;

  return <main className="customer-portal-shell"><section className="customer-portal-card customer-portal-wide"><div className="portal-header"><div><span className="eyebrow">Área do cliente</span><h1>Olá, {session.customer.nome}</h1><p className="login-copy">Solicite atendimento e acompanhe suas ordens.</p></div><button className="secondary-button" type="button" onClick={onBack}>Sair</button></div><div className="portal-grid"><form className="entity-form portal-order-form" onSubmit={submitOrder}><h2>Nova solicitação</h2><label>Equipamento<input name="equipamento" value={orderForm.equipamento} onChange={(event) => update(event, setOrderForm)} placeholder="Notebook, celular, console..." required /></label><label>Relato do erro ou defeito<textarea name="defeito" rows="5" value={orderForm.defeito} onChange={(event) => update(event, setOrderForm)} required /></label><label>Forma de pagamento<select name="forma_pagamento" value={orderForm.forma_pagamento} onChange={(event) => update(event, setOrderForm)}><option>Pix</option><option>Cartão Crédito</option><option>Cartão Débito</option><option>Boleto</option><option>Outro</option></select></label><button className="primary-button" type="submit">Gerar ordem interna</button></form><section><h2>Minhas ordens</h2><div className="portal-orders">{orders.map((order) => <article className="portal-order-item" key={order.id}><div><strong>{order.protocolo}</strong><h3>{order.equipamento}</h3><span>{order.status} · R$ {Number(order.valor_total || 120).toFixed(2)}</span></div><button className="secondary-button" type="button" onClick={() => loadLabel(order)}>Etiqueta de envio</button></article>)}{!orders.length && <p className="empty-state">Nenhuma ordem aberta ainda.</p>}</div></section></div>{message && <p className="portal-success">{message}</p>}{error && <p className="form-error">{error}</p>}</section>{shippingLabel && <div className="modal-backdrop"><div className="modal-panel shipping-label-modal"><div className="modal-header"><div><span className="eyebrow">Etiqueta de envio</span><h2>{shippingLabel.protocolo}</h2></div><button className="ghost-button" type="button" onClick={() => setShippingLabel(null)}>Fechar</button></div><div className="shipping-label-content"><strong>{shippingLabel.cliente}</strong><span>{shippingLabel.documento}</span><span>{shippingLabel.telefone}</span><span>{shippingLabel.email}</span><hr /><strong>Equipamento: {shippingLabel.equipamento}</strong><span>Defeito: {shippingLabel.defeito}</span><span>Status: {shippingLabel.status}</span></div><button className="primary-button" type="button" onClick={() => window.print()}>Imprimir etiqueta</button></div></div>}</main>;
}
